---
title: "Data Visualization"
author: "Rachael E. Blake"
date: "May 1, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r, include=FALSE, echo=FALSE, results='hide'}
library(ggplot2) ; library(tidyverse) ; library(gridExtra) ; library(grid)

```

```{r, echo=FALSE, include=FALSE}
# PDO data
source("PDO_cleaning.r")

# dataframes are pdo_mon and pdo_ann

pdo_mon_adj <- pdo_mon %>%
               mutate(Month_number = forcats::fct_recode(Month, "01"="JAN", "02"="FEB", "03"="MAR",
                                                                "04"="APR", "05"="MAY", "06"="JUN", 
                                                                "07"="JUL", "08"="AUG", "09"="SEP", 
                                                                "10"="OCT", "11"="NOV", "12"="DEC"),
                      Yr_Mn = paste(Year, Month_number, sep="-"),
                      Sign = ifelse(PDO>0, "A", "B"))
               
```

```{r, echo=FALSE}
# PDO plots
pdo_plot <- ggplot(data=pdo_mon, aes(x=YEAR, y=PDO)) + geom_col() + 
            geom_hline(yintercept=0, size=1.5) + ylab("PDO Index")

  
#
pdo_plot2 <- ggplot(data=pdo_mon_adj, aes(x=Yr_Mn, y=PDO)) + 
             geom_col(aes(fill=Sign)) + xlab("Year") +            #, show.legend=FALSE
             geom_hline(yintercept=0, size=1) + ylab("PDO Index") + 
             scale_x_discrete(breaks=c("1998-01","1999-01", "2000-01", "2001-01", "2002-01", "2003-01",
                                       "2004-01", "2005-01", "2006-01", "2007-01", "2008-01", "2009-01", 
                                       "2010-01", "2011-01", "2012-01", "2013-01", "2014-01", "2015-01", 
                                       "2016-01"),
                              labels=c("1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005",
                                       "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013",
                                       "2014","2015", "2016"))

```

```{r, echo=FALSE, include=FALSE}
# Freshwater Discharge Hill Model data
source("Fresh_Discharge_cleaning.r")

# dataframes are FWD_ann_mn and FWD_mon_mn

```

```{r, echo=FALSE}
fwd_plot <- ggplot(data=FWD_ann_mn, aes(x=YEAR, y=(mean_yearly_anomaly*10))) + 
            geom_col(aes(fill=Sign)) + ylab("Yearly Anomaly") + theme_bw() +
            geom_hline(yintercept=0, size=1) + 
            scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                              name="",
                              labels=c("positive runoff", "negative runoff")) 
 
  
fwd_plot2 <- ggplot(data=FWD_mon_mn, aes(x=Year_Month, y=mean_monthly_anomaly)) + 
             geom_col(aes(fill=Sign)) + xlab("Year") + ylab("Anomaly") + 
             geom_hline(yintercept=0, size=1) +  
             scale_x_discrete(breaks=c("1998-01", "1999-01", "2000-01", "2001-01", "2002-01", "2003-01",
                                       "2004-01", "2005-01", "2006-01", "2007-01", "2008-01", 
                                       "2009-01", "2010-01", "2011-01", "2012-01", "2013-01", 
                                       "2014-01", "2015-01", "2016-01"),
                              labels=c("1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005",
                                       "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013",
                                       "2014","2015", "2016"),
                              limits=c(levels(FWD_mon_mn$Year_Month)))
                             

```

```{r, echo=FALSE, include=FALSE}
# source air temperature cleaning script
source("AirTemp_cleaning.r")

# dataframes in this script are
# spring_a_temp, summer_a_temp, fall_a_temp, winter_a_temp, ann_a_temp

```

```{r, echo=FALSE}
# plot of annual air temp anomalies

ann_a_temp$YrMnDy <- as.factor(ann_a_temp$YrMnDy)

ann_a_temp2 <- ann_a_temp %>%
               dplyr::select(YrMn, Month_Anom, Month_Sign) %>%
               dplyr::distinct()

ann_air <- ggplot(data=ann_a_temp2, aes(x=YrMn, y=Month_Anom)) + 
           geom_col(aes(fill=Month_Sign)) + ylab("Anomaly") + xlab("Year") + 
           geom_hline(yintercept=0, size=1) + 
           scale_x_discrete(breaks=c("1999-01", "2000-01", "2001-01", "2002-01","2003-01", 
                                     "2004-01", "2005-01", "2006-01", "2007-01", "2008-01", 
                                     "2009-01", "2010-01", "2011-01", "2012-01", "2013-01", 
                                     "2014-01", "2015-01", "2016-01"),
                            labels=c("1999", "2000", "2001", "2002", "2003", "2004", "2005", 
                                     "2006", "2007", "2008", "2009", "2010", "2011", "2012", 
                                     "2013", "2014","2015", "2016"),
                            limits=c(levels(ann_a_temp$YrMn)))



```

```{r, echo=FALSE, include=FALSE}
# source air temperature cleaning script
source("WaterTemp_cleaning.r")

# dataframes in this script are
# WTemp_all, WTemp_Yr, WTemp_June, WTemp_Dec

```


#Invertebrates: Percent Cover Data
```{r, include=FALSE, echo=FALSE, results='hide'}
# source the data cleaning script
source("Data_Cleaning_K_Bay_ALL.r")

AllData_clean2 <- AllData_clean %>% 
                  dplyr::select(-FUCUS_NUM_ADULTS, -FUCUS_SPORELINGS_NUM) %>%
                  dplyr::mutate(MASTO_PAP = str_replace_all(MASTO_PAP, ",",""),
                                SIPHONARIA = gsub("[*]", "", SIPHONARIA)
                             ) %>%
                  dplyr::filter(PTEROSIPHONIA != "tr") %>%
                  dplyr::mutate_at(c(5:57), funs(as.numeric)) # converts select columns

```

```{r, echo=FALSE}
# dataframe is called AllData_clean

PerCov_long <- AllData_clean2 %>%
               gather(TAXA, PER_COV_OR_COUNT, -YEAR, -TRIPLET, -QUAD, -TREATMENT)

PerCov_anom <- PerCov_long %>%
               dplyr::select(-TRIPLET, -QUAD) %>%
               dplyr::filter(TREATMENT == "CONTROL") %>%
               dplyr::mutate_at(c(4), funs(as.numeric)) %>% # converts select columns
               dplyr::group_by(TAXA) %>%
               dplyr::mutate(TAXA_Mean = mean(PER_COV_OR_COUNT),
                             ANOMALY = PER_COV_OR_COUNT-TAXA_Mean) %>%
               dplyr::ungroup() %>%
               dplyr::group_by(TAXA, YEAR) %>%
               dplyr::mutate(YEAR_Mean = mean(PER_COV_OR_COUNT),
                             YEAR_Anom = mean(YEAR_Mean-TAXA_Mean),
                             YEAR_Anom_Scale = YEAR_Anom/100,
                             YEAR_Anom_Scale2 = YEAR_Anom/10) %>%
               dplyr::ungroup() %>%
               dplyr::arrange(YEAR, TREATMENT, TAXA)

```

```{r, echo=FALSE}
explore_plots <- function(y_var){
                 p <- ggplot(data=AllData_clean2, aes_string(x="YEAR", y=y_var, fill="TREATMENT")) + 
                      geom_boxplot() + theme(legend.position="top", legend.title=element_blank()) +
                      scale_fill_manual(breaks=c("CONTROL","SCRAPE99","SCRAPE00"),
                                        labels=c("Control","Scrape 1999","Scrape 2000"),
                                        values=c("#76eec6","#63b8ff","#ff6a6a"))
                 return(p)
}


 

```

```{r, echo=FALSE, fig.height=3.5, fig.width=7}
# Fucus Total
# ft <- explore_plots("FUCUS_PERCOV_TOTAL")
# ft

# make a plot for each variable
var_names <- names(AllData_clean2[,c(5:57)]) 

lapply(var_names, function(x) FUN=explore_plots(y_var=x))

```

```{r, echo=FALSE, eval=FALSE}
# Mussel anomaly plot
anom_muss <- ggplot(data=PerCov_anom[PerCov_anom$TAXA == "MYTILUS",]) + 
             geom_col(aes(x=YEAR,y=YEAR_Anom_Scale))

# Fucus anomaly plot
anom_fucu <- ggplot(data=PerCov_anom[PerCov_anom$TAXA == "FUCUS_PERCOV_TOTAL",]) + 
             geom_col(aes(x=YEAR,y=YEAR_Anom_Scale))

```

```{r, echo=FALSE, fig.height=5, fig.width=8}
# combined PDO and mussel anomaly plot
anom_pdo_muss <- pdo_plot2 + 
                 geom_col(data=PerCov_anom[PerCov_anom$TAXA == "MYTILUS",], 
                          aes(x=YEAR,y=YEAR_Anom_Scale, color="#696366"), width=2) +    #show.legend=TRUE   
                 ylab("Anomaly") + theme_bw() + ylim(-4,4) +
                 scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                                   name="",
                                   labels=c("positive PDO", "negative PDO")) +
                 scale_color_manual(values="#595959", name="", labels="MYTILUS % cover") + 
                 theme(panel.grid.major=element_blank(),
                       panel.grid.minor=element_blank(),
                       panel.border=element_blank(),
                       legend.position=c(.92, .15),
                       legend.margin=margin(t=-0.8, unit="cm"),
                       axis.text = element_text(size=10),
                       axis.title = element_text(size=16),
                       axis.line = element_line(colour='black', size=0.5, linetype='solid'))
anom_pdo_muss

# combined PDO and Fucus anomaly plot
anom_pdo_fucu <- pdo_plot2 + 
                 geom_col(data=PerCov_anom[PerCov_anom$TAXA == "FUCUS_PERCOV_TOTAL",], 
                          aes(x=YEAR,y=YEAR_Anom_Scale, color="#696366"), width=2) + 
                 ylab("Anomaly") + theme_bw() + ylim(-4,4) +
                 scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                                   name="",
                                   labels=c("positive PDO", "negative PDO")) +
                 scale_color_manual(values="#595959", labels="Fucus % cover") + 
                 theme(panel.grid.major=element_blank(),
                       panel.grid.minor=element_blank(),
                       panel.border=element_blank(),
                       legend.position=c(.92, .15),
                       legend.margin=margin(t=-0.8, unit="cm"),
                       axis.text = element_text(size=10),
                       axis.title = element_text(size=16),
                       axis.line = element_line(colour = 'black', size=0.5, linetype='solid'))
anom_pdo_fucu

# combined PDO and Barnacles anomaly plot
anom_pdo_barn <- pdo_plot2 + 
                 geom_col(data=PerCov_anom[PerCov_anom$TAXA == "BARNACLES",], 
                          aes(x=YEAR, y=YEAR_Anom_Scale, color="#696366"), width=2) + 
                 ylab("Anomaly") + theme_bw() + ylim(-4,4) +
                 scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                                   name="",
                                   labels=c("positive PDO", "negative PDO")) +
                 scale_color_manual(values="#595959", labels="Barnacle % cover") + 
                 theme(panel.grid.major=element_blank(),
                       panel.grid.minor=element_blank(),
                       panel.border=element_blank(),
                       legend.position=c(.92, .15),
                       legend.margin=margin(t=-0.8, unit="cm"),
                       axis.text = element_text(size=10),
                       axis.title = element_text(size=16),
                       axis.line = element_line(colour = 'black', size=0.5, linetype='solid'))
anom_pdo_barn


```

```{r, echo=FALSE, fig.height=5, fig.width=8}
# combined freshwater discharge and invert plots
myt_sub <- unique(PerCov_anom[PerCov_anom$TAXA == "MYTILUS",c(2,9,10)])
myt_sub <- dplyr::mutate(myt_sub, YEAR_Mon = paste(YEAR,"-06", sep=""))
myt_sub$YEAR <- as.factor(myt_sub$YEAR)


fwdplot_myt <- fwd_plot2 + 
               geom_col(data=myt_sub, 
                        aes(x=YEAR_Mon, y=YEAR_Anom_Scale, color="#696366"), width=2) +    #show.legend=TRUE   
               ylab("Anomaly") + xlab("Year") + theme_bw() + ylim(-0.45,0.45) + 
               scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                                 name="",
                                 labels=c("positive runoff", "negative runoff")) +
               scale_color_manual(values="#595959", name="", labels="Mytilus % cover") +
               theme(panel.grid.major=element_blank(),
                     panel.grid.minor=element_blank(),
                     panel.border=element_blank(),
                     legend.position=c(.22, .15),
                     legend.margin=margin(t=-0.8, unit="cm"),
                     axis.text = element_text(size=10),
                     axis.title = element_text(size=16),
                     axis.line = element_line(colour = 'black', size=0.5, linetype='solid'))
fwdplot_myt

###
fuc_sub <- unique(PerCov_anom[PerCov_anom$TAXA == "FUCUS_PERCOV_TOTAL",c(2,9,10)])
fuc_sub <- dplyr::mutate(fuc_sub, YEAR_Mon = paste(YEAR,"-06", sep=""))
fuc_sub$YEAR <- as.factor(fuc_sub$YEAR)

fwdplot_fuc <- fwd_plot2 + 
               geom_col(data=fuc_sub, 
                        aes(x=YEAR_Mon, y=YEAR_Anom_Scale, color="#696366"), width=2) +    #show.legend=TRUE   
               ylab("Anomaly") + xlab("Year") + theme_bw() + ylim(-0.45,0.45) + 
               scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                                 name="",
                                 labels=c("positive runoff", "negative runoff")) +
               scale_color_manual(values="#595959", name="", labels="Fucus % cover") +
               theme(panel.grid.major=element_blank(),
                     panel.grid.minor=element_blank(),
                     panel.border=element_blank(),
                     legend.position=c(.22, .15),
                     legend.margin=margin(t=-0.8, unit="cm"),
                     axis.text = element_text(size=10),
                     axis.title = element_text(size=16),
                     axis.line = element_line(colour = 'black', size=0.5, linetype='solid'))
fwdplot_fuc

###
brn_sub <- unique(PerCov_anom[PerCov_anom$TAXA == "BARNACLES",c(2,9,10)])
brn_sub <- dplyr::mutate(brn_sub, YEAR_Mon = paste(YEAR,"-06", sep=""))
brn_sub$YEAR <- as.factor(brn_sub$YEAR)

fwdplot_brn <- fwd_plot2 + 
               geom_col(data=brn_sub, 
                        aes(x=YEAR_Mon, y=YEAR_Anom_Scale, color="#696366"), width=2) +    #show.legend=TRUE   
               ylab("Anomaly") + xlab("Year") + theme_bw() + ylim(-0.45,0.45) + 
               scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                                 name="",
                                 labels=c("positive runoff", "negative runoff")) +
               scale_color_manual(values="#595959", name="", labels="Barnacle % cover") +
               theme(panel.grid.major=element_blank(),
                     panel.grid.minor=element_blank(),
                     panel.border=element_blank(),
                     legend.position=c(.22, .15),
                     legend.margin=margin(t=-0.8, unit="cm"),
                     axis.text = element_text(size=10),
                     axis.title = element_text(size=16),
                     axis.line = element_line(colour = 'black', size=0.5, linetype='solid'))
fwdplot_brn

```


```{r, echo=FALSE}
# subsetting and arranging data for temperature plots below
myt_sub2 <- PerCov_anom %>%
            dplyr::filter(TAXA == "MYTILUS") %>%
            dplyr::mutate(YEAR_Mon = paste(YEAR,"-06", sep="")) %>%
            dplyr::select(YEAR, YEAR_Anom, YEAR_Anom_Scale2, YEAR_Mon) %>%
            dplyr::distinct()
            
myt_sub2$YEAR <- as.factor(myt_sub2$YEAR)
#

fuc_sub2 <- PerCov_anom %>%
            dplyr::filter(TAXA == "FUCUS_PERCOV_TOTAL") %>%
            dplyr::mutate(YEAR_Mon = paste(YEAR,"-06", sep="")) %>%
            dplyr::select(YEAR, YEAR_Anom, YEAR_Anom_Scale2, YEAR_Mon) %>%
            dplyr::distinct()
            
fuc_sub2$YEAR <- as.factor(fuc_sub2$YEAR)
#

brn_sub2 <- PerCov_anom %>%
            dplyr::filter(TAXA == "BARNACLES") %>%
            dplyr::mutate(YEAR_Mon = paste(YEAR,"-06", sep="")) %>%
            dplyr::select(YEAR, YEAR_Anom, YEAR_Anom_Scale2, YEAR_Mon) %>%
            dplyr::distinct()
            
brn_sub2$YEAR <- as.factor(brn_sub2$YEAR)

```


```{r, echo=FALSE}
# plots of invert percent cover for over-plotting below
myt <- ggplot(data=myt_sub2, aes(x=YEAR, y=YEAR_Anom)) + 
       geom_col(width=0.25, alpha=0.5) + theme_bw() + 
       geom_hline(yintercept=0, size=0.5)

fuc <- ggplot(data=fuc_sub2, aes(x=YEAR, y=YEAR_Anom)) + 
       geom_col(width=0.25, alpha=0.5) + theme_bw() + 
       geom_hline(yintercept=0, size=0.5)

brn <- ggplot(data=brn_sub2, aes(x=YEAR, y=YEAR_Anom)) + 
       geom_col(width=0.25, alpha=0.5) + theme_bw() + 
       geom_hline(yintercept=0, size=0.5)

```

```{r, echo=FALSE}
# plots of air temperature - data only available 2003-2016

spr <- myt +
       geom_point(data=spring_a_temp, aes(x=Year, y=Num_Day_Less_0), size=2) + #geom_point(size=2) + 
       theme_bw() + ylab("# of days air temp < 0 C") +
       labs(title="Spring (Mar, Apr, May) number of cold days") +
       theme(plot.title=element_text(size=10),
             panel.grid.minor=element_blank(),
             axis.text.x=element_text(angle=30, hjust=1))

sprf <- fuc +
        geom_point(data=spring_a_temp, aes(x=Year, y=Num_Day_Less_0), size=2) + #geom_point(size=2) + 
        theme_bw() + ylab("# of days air temp < 0 C") +
        labs(title="Spring (Mar, Apr, May) number of cold days") +
        theme(plot.title=element_text(size=10),
              panel.grid.minor=element_blank(),
              axis.text.x=element_text(angle=30, hjust=1))

sprb <- brn +
        geom_point(data=spring_a_temp, aes(x=Year, y=Num_Day_Less_0), size=2) + #geom_point(size=2) + 
        theme_bw() + ylab("# of days air temp < 0 C") + ylim(-15, 35) +
        labs(title="Spring (Mar, Apr, May) number of cold days") +
        theme(plot.title=element_text(size=10),
              panel.grid.minor=element_blank(),
              axis.text.x=element_text(angle=30, hjust=1))
###

sum <- myt +
       geom_point(data=summer_a_temp, aes(x=Year, y=Num_Day_More_15), size=2) + #geom_point(size=2) +
       theme_bw() + ylab("# of days air temp > 15 C") +
       labs(title="Summer (Jun, Jul, Aug) number of hot days") +
       theme(plot.title=element_text(size=10),
             panel.grid.minor=element_blank(),
             axis.text.x=element_text(angle=30, hjust=1))

sumf <- fuc +
        geom_point(data=summer_a_temp, aes(x=Year, y=Num_Day_More_15), size=2) + #geom_point(size=2) +
        theme_bw() + ylab("# of days air temp > 15 C") +
        labs(title="Summer (Jun, Jul, Aug) number of hot days") +
        theme(plot.title=element_text(size=10),
              panel.grid.minor=element_blank(),
              axis.text.x=element_text(angle=30, hjust=1))

sumb <- brn +
        geom_point(data=summer_a_temp, aes(x=Year, y=Num_Day_More_15), size=2) + #geom_point(size=2) +
        theme_bw() + ylab("# of days air temp > 15 C") + ylim(-15, 35) +
        labs(title="Summer (Jun, Jul, Aug) number of hot days") +
        theme(plot.title=element_text(size=10),
              panel.grid.minor=element_blank(),
              axis.text.x=element_text(angle=30, hjust=1))

###

fal <- myt +
       geom_point(data=fall_a_temp, aes(x=Year, y=Num_Day_Less_0), size=2) + #geom_point(size=2) +
       theme_bw() + ylab("# of days air temp < 0 C") +
       labs(title="Fall (Sep, Oct, Nov) number of cold days") +
       theme(plot.title=element_text(size=10),
             panel.grid.minor=element_blank(),
             axis.text.x=element_text(angle=30, hjust=1))

falf <- fuc +
        geom_point(data=fall_a_temp, aes(x=Year, y=Num_Day_Less_0), size=2) + #geom_point(size=2) +
        theme_bw() + ylab("# of days air temp < 0 C") +
        labs(title="Fall (Sep, Oct, Nov) number of cold days") +
        theme(plot.title=element_text(size=10),
              panel.grid.minor=element_blank(),
              axis.text.x=element_text(angle=30, hjust=1))

falb <- brn +
        geom_point(data=fall_a_temp, aes(x=Year, y=Num_Day_Less_0), size=2) + #geom_point(size=2) +
        theme_bw() + ylab("# of days air temp < 0 C") + ylim(-15, 35) +
        labs(title="Fall (Sep, Oct, Nov) number of cold days") +
        theme(plot.title=element_text(size=10),
              panel.grid.minor=element_blank(),
              axis.text.x=element_text(angle=30, hjust=1))

###

win <- myt +
       geom_point(data=winter_a_temp, aes(x=Year, y=Num_Day_Less_neg10), size=2) + #geom_point(size=2) +
       theme_bw() + ylab("# of days air temp < -10 C") +
       labs(title="Winter (Dec, Jan, Feb) number of cold days") +
       theme(plot.title=element_text(size=10),
             panel.grid.minor=element_blank(),
             axis.text.x=element_text(angle=30, hjust=1))

winf <- fuc +
        geom_point(data=winter_a_temp, aes(x=Year, y=Num_Day_Less_neg10), size=2) + #geom_point(size=2) +
        theme_bw() + ylab("# of days air temp < -10 C") +
        labs(title="Winter (Dec, Jan, Feb) number of cold days") +
        theme(plot.title=element_text(size=10),
              panel.grid.minor=element_blank(),
              axis.text.x=element_text(angle=30, hjust=1))

winb <- brn +
        geom_point(data=winter_a_temp, aes(x=Year, y=Num_Day_Less_neg10), size=2) + #geom_point(size=2) +
        theme_bw() + ylab("# of days air temp < -10 C") + ylim(-15, 35) +
        labs(title="Winter (Dec, Jan, Feb) number of cold days") +
        theme(plot.title=element_text(size=10),
              panel.grid.minor=element_blank(),
              axis.text.x=element_text(angle=30, hjust=1))

```

### Mytilus
```{r, echo=FALSE, fig.height=7, fig.width=8}
# arranging above plots
grid.arrange(spr, fal, sum, win)

```

### Fucus
```{r, echo=FALSE, fig.height=7, fig.width=8}
# arranging above plots
grid.arrange(sprf, falf, sumf, winf)

```

### Barnacles
```{r, echo=FALSE, fig.height=7, fig.width=8}
# arranging above plots
grid.arrange(sprb, falb, sumb, winb)

```

```{r, echo=FALSE}
# plots of air temperature anomalies

spr2 <- ggplot(data=spring_a_temp, aes(x=YrMnDy, y=Month_Anom)) + 
        geom_col(aes(fill=Month_Sign)) + ylab("Anomaly") + xlab("Year") + 
        theme_bw() + geom_hline(yintercept=0, size=1) + 
        labs(title="Spring Air Temp") + 
        theme(legend.position=c(.20, .2), legend.background = element_rect(fill="transparent"),
              legend.key.size=unit(0.3, "cm"), axis.text.x=element_text(angle=30, hjust=1),
              panel.grid=element_blank()) +
        scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                          name="",
                          labels=c("positive temp", "negative temp")) +
        scale_x_discrete(breaks=c("1999-03-01", "2000-03-01", "2001-03-01", "2002-03-01", "2003-03-01",
                                  "2004-03-01", "2005-03-01", "2006-03-01", "2007-03-01", "2008-03-01",
                                  "2009-03-01", "2010-03-01", "2011-03-01", "2012-03-01", "2013-03-01",
                                  "2014-03-01", "2015-03-01", "2016-03-01"),
                         labels=c("1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007",
                                  "2008", "2009", "2010", "2011", "2012", "2013", "2014","2015", "2016"))

sum2 <- ggplot(data=summer_a_temp, aes(x=YrMnDy, y=Month_Anom)) + 
        geom_col(aes(fill=Month_Sign)) + ylab("Anomaly") + xlab("Year") + 
        theme_bw() + geom_hline(yintercept=0, size=1) + 
        labs(title="Summer Air Temp") + 
        theme(legend.position=c(.2, .2), legend.background = element_rect(fill="transparent"),
              legend.key.size=unit(0.3, "cm"), axis.text.x=element_text(angle=30, hjust=1),
              panel.grid=element_blank()) +
        scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                          name="",
                          labels=c("positive temp", "negative temp")) +
        scale_x_discrete(breaks=c("1999-06-01", "2000-06-01", "2001-06-01", "2002-06-01", "2003-06-01",
                                  "2004-06-01", "2005-06-01", "2006-06-01", "2007-06-01", "2008-06-01",
                                  "2009-06-01", "2010-06-01", "2011-06-01", "2012-06-01", "2013-06-01",
                                  "2014-06-01", "2015-06-01", "2016-06-01"),
                         labels=c("1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007",
                                  "2008", "2009", "2010", "2011", "2012", "2013", "2014","2015", "2016"))

fal2 <- ggplot(data=fall_a_temp, aes(x=YrMnDy, y=Month_Anom)) + 
        geom_col(aes(fill=Month_Sign)) + ylab("Anomaly") + xlab("Year") + 
        theme_bw() + geom_hline(yintercept=0, size=1) + 
        labs(title="Fall Air Temp") + 
        theme(legend.position=c(.875, .2), legend.background = element_rect(fill="transparent"),
              legend.key.size=unit(0.3, "cm"), axis.text.x=element_text(angle=30, hjust=1),
              panel.grid=element_blank()) +
        scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                          name="",
                          labels=c("positive temp", "negative temp")) +
        scale_x_discrete(breaks=c("1999-09-01", "2000-09-01", "2001-09-01", "2002-09-01", "2003-09-01",
                                  "2004-09-01", "2005-09-01", "2006-09-01", "2007-09-01", "2008-09-01",
                                  "2009-09-01", "2010-09-01", "2011-09-01", "2012-09-01", "2013-09-01",
                                  "2014-09-01", "2015-09-01", "2016-09-01"),
                         labels=c("1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007",
                                  "2008", "2009", "2010", "2011", "2012", "2013", "2014","2015", "2016"))


win2 <- ggplot(data=winter_a_temp, aes(x=YrMnDy, y=Month_Anom)) + 
        geom_col(aes(fill=Month_Sign)) + ylab("Anomaly") + xlab("Year") + 
        theme_bw() + geom_hline(yintercept=0, size=1) + 
        labs(title="Winter Air Temp") + 
        theme(legend.position=c(.32, .2), legend.background = element_rect(fill="transparent"),
              legend.key.size=unit(0.3, "cm"), axis.text.x=element_text(angle=30, hjust=1),
              panel.grid=element_blank()) +
        scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                          name="",
                          labels=c("positive temp", "negative temp")) +
        scale_x_discrete(breaks=c("1999-12-01", "2000-12-01", "2001-12-01", "2002-12-01", "2003-12-01",
                                  "2004-12-01", "2005-12-01", "2006-12-01", "2007-12-01", "2008-12-01",
                                  "2009-12-01", "2010-12-01", "2011-12-01", "2012-12-01", "2013-12-01",
                                  "2014-12-01", "2015-12-01", "2016-12-01"),
                         labels=c("1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007",
                                  "2008", "2009", "2010", "2011", "2012", "2013", "2014","2015", "2016"))


```

```{r, echo=FALSE, fig.height=7, fig.width=8}
# arranging above plots
grid.arrange(spr2, fal2, sum2, win2)

```

```{r, echo=FALSE}

at_myt <- ann_air + 
          geom_col(data=myt_sub2, 
                   aes(x=YEAR_Mon,y=YEAR_Anom_Scale2, color="#696366"), width=2) +    #show.legend=TRUE   
          ylab("Anomaly") + theme_bw() + ylim(-14,14) + 
          scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                            name="",
                            labels=c("positive temp C", "negative temp C")) +
          scale_color_manual(values="#595959", name="", labels="Mytilus % cover") + 
          theme(panel.grid=element_blank(),
                panel.border=element_blank(),
                legend.position=c(.85, .15),
                legend.margin=margin(t=-0.8, unit="cm"),
                legend.background = element_rect(fill="transparent"),
                legend.key.size=unit(0.5, "cm"),
                axis.text = element_text(size=10),
                axis.title = element_text(size=16),
                axis.line = element_line(colour='black', size=0.5, linetype='solid'))

at_myt
###

at_fuc <- ann_air + 
          geom_col(data=fuc_sub2, 
                   aes(x=YEAR_Mon,y=YEAR_Anom_Scale2, color="#696366"), width=2) +    #show.legend=TRUE   
          ylab("Anomaly") + theme_bw() + ylim(-14,14) + 
          scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                            name="",
                            labels=c("positive temp C", "negative temp C")) +
          scale_color_manual(values="#595959", name="", labels="Fucus % cover") + 
          theme(panel.grid=element_blank(),
                panel.border=element_blank(),
                legend.position=c(.85, .15),
                legend.margin=margin(t=-0.8, unit="cm"),
                legend.background = element_rect(fill="transparent"),
                legend.key.size=unit(0.5, "cm"),
                axis.text = element_text(size=10),
                axis.title = element_text(size=16),
                axis.line = element_line(colour='black', size=0.5, linetype='solid'))

at_fuc
###

at_brn <- ann_air + 
          geom_col(data=brn_sub2, 
                   aes(x=YEAR_Mon,y=YEAR_Anom_Scale2, color="#696366"), width=2) +    #show.legend=TRUE   
          ylab("Anomaly") + theme_bw() + ylim(-14,14) + 
          scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                            name="",
                            labels=c("positive temp C", "negative temp C")) +
          scale_color_manual(values="#595959", name="", labels="Barnacle % cover") + 
          theme(panel.grid=element_blank(),
                panel.border=element_blank(),
                legend.position=c(.85, .15),
                legend.margin=margin(t=-0.8, unit="cm"),
                legend.background = element_rect(fill="transparent"),
                legend.key.size=unit(0.5, "cm"),
                axis.text = element_text(size=10),
                axis.title = element_text(size=16),
                axis.line = element_line(colour='black', size=0.5, linetype='solid'))

at_brn



```


# NMDS Plots
```{r, echo=FALSE, include=FALSE}
source("NMDS_analysis.r")

# need to use NMDS output percov_mds$points

```
### PDO
```{r, echo=FALSE, fig.height=7, fig.width=8}
# prettier plotting
# build a data frame with NMDS coordinates and metadata
NMDS_ord <- data.frame(NMDS1 = percov_mds$points[,1], NMDS2 = percov_mds$points[,2],
                       PDO_Sign = PerCov_PDO$PDO_Sign, YEAR = PerCov_PDO$Year)

# now the plot
ord1 <- ggplot(NMDS_ord, aes(x=NMDS1, y=NMDS2, color=PDO_Sign)) +
        geom_point() + stat_ellipse() +
        theme_bw() + #labs(title = "NMDS Plot by PDO") + 
        scale_color_manual(values=c("A"="#f88379", "B"="#00BFC4"), name="",
                           labels=c("positive PDO","negative PDO")) + 
        theme(panel.grid.major=element_blank(),
              panel.grid.minor=element_blank())
ord1

ord2 <- ggplot(NMDS_ord, aes(x=NMDS1, y=NMDS2, color=YEAR)) +
        geom_point() + #stat_ellipse() +
        theme_bw() + labs(title = "NMDS Plot by Year")


```

```{r, echo=FALSE}
percov_perm
```

### Freshwater
```{r, echo=FALSE, fig.height=7, fig.width=8}
# prettier plotting
# build a data frame with NMDS coordinates and metadata
NMDS_ord2 <- data.frame(NMDS1 = percov_mds2$points[,1], NMDS2 = percov_mds2$points[,2],
                        YEAR = fresh_treats$Year, FWD_Anom_Sign = fresh_treats$FWD_Sign)

# now the plot
ord3 <- ggplot(NMDS_ord2, aes(x=NMDS1, y=NMDS2, color=FWD_Anom_Sign)) +
        geom_point() + stat_ellipse() +
        theme_bw() + 
        scale_color_manual(values=c("A"="#f88379", "B"="#00BFC4"), name="",
                           labels=c("positive FWD Anom","negative FWD Anom")) + 
        theme(panel.grid.major=element_blank(),
              panel.grid.minor=element_blank())
ord3


```

```{r, echo=FALSE}
percov_perm2
```

### Air Temp
```{r, echo=FALSE, fig.height=7, fig.width=8}
# prettier plotting
# build a data frame with NMDS coordinates and metadata
NMDS_ord3 <- data.frame(NMDS1 = percov_mds3$points[,1], NMDS2 = percov_mds3$points[,2],
                        YEAR = atemp_treats$Year, ATmp_Anom_Sign = atemp_treats$ATmp_Sign)

# now the plot
ord4 <- ggplot(NMDS_ord3, aes(x=NMDS1, y=NMDS2, color=ATmp_Anom_Sign)) +
        geom_point() + stat_ellipse() +
        theme_bw() + 
        scale_color_manual(values=c("A"="#f88379", "B"="#00BFC4"), name="",
                           labels=c("positive Air Temp Anom","negative Air Temp Anom")) + 
        theme(panel.grid.major=element_blank(),
              panel.grid.minor=element_blank())
ord4


```

```{r, echo=FALSE}
percov_perm3
```

### All env. variables
```{r, echo=FALSE, fig.height=6, fig.width=8}
# prettier plotting
# build a data frame with NMDS coordinates and metadata
NMDS_ord4 <- data.frame(NMDS1 = percov_mds4$points[,1], NMDS2 = percov_mds4$points[,2],
                        YEAR = all_treats$Year, ATmp_Anom_Sign = all_treats$ATmp_Sign,
                        FWD_annSign = all_treats$FWD_Sign, PDOSign = all_treats$PDO_Sign)

# now the plot
ord5 <- ggplot(NMDS_ord4, aes(x=NMDS1, y=NMDS2, color=ATmp_Anom_Sign, shape=FWD_annSign)) +
        geom_point(size=4) + #stat_ellipse() +
        theme_bw() + 
        scale_color_manual(values=c("A"="#FF0000", "B"="#00FFFF"), name="",
                           labels=c("positive Air Temp anom","negative Air Temp anom")) + 
        scale_shape_manual(values=c("A"=16, "B"=17), name="",
                           labels=c("positive runoff anom", "negative runoff anom")) +
        theme(panel.grid.major=element_blank(),
              panel.grid.minor=element_blank())
ord5


```

```{r, echo=FALSE}
percov_perm4
```

### Biological NMDS
```{r, echo=FALSE, fig.height=7, fig.width=10}
# prettier plotting
# build a data frame with NMDS coordinates and metadata
NMDS_ord5 <- data.frame(NMDS1 = percov_mds5$points[,1], NMDS2 = percov_mds5$points[,2],
                        YEAR = all_treats2$Year, QUAD = all_treats2$QUAD, 
                        FWD_Disc = round(all_treats2$mn_yr_discharge, digits=2), 
                        FWD_annSign = all_treats2$FWD_Sign,
                        ATmp_Anom_Sign = all_treats2$ATmp_Sign, ATemp_YearMn = round(all_treats2$ATemp_YearMn),
                        Water_Temp_June = round(all_treats2$Water_Temp_June), PDOSign = all_treats2$PDO_Sign)

# make convex hulls for each plot across all years
find_hull <- function(df) df[chull(df$NMDS1, df$NMDS2), ]
hulls_all <- ddply(NMDS_ord5, "QUAD", find_hull)

# now the plot
ord6 <- ggplot(NMDS_ord5, aes(x=NMDS1, y=NMDS2, color=QUAD)) +
        geom_point(size=4) + theme_bw() + 
        geom_polygon(data=hulls_all, aes(fill=QUAD), alpha=0.3, size=1) +
        theme(panel.grid.major=element_blank(),
              panel.grid.minor=element_blank())
ord6

# make convex hulls for each year across all plots
hulls_all2 <- ddply(NMDS_ord5, "YEAR", find_hull)

# now the plot
ord7 <- ggplot(NMDS_ord5, aes(x=NMDS1, y=NMDS2, color=YEAR)) +
        geom_point(size=4) + theme_bw() + 
        geom_polygon(data=hulls_all2, aes(fill=YEAR), alpha=0.3, size=1) +
        theme(panel.grid.major=element_blank(),
              panel.grid.minor=element_blank())
ord7

##
# now the plot
vecs5 <- vegan::envfit(percov_mds5$points, sp_percov5, perm=1000)
vecs5
sp_vecs <- as.data.frame(vegan::scores(vecs5, display="vectors"))
sp_vecs <- cbind(sp_vecs, Species = rownames(sp_vecs))


ord8 <- ggplot(data=NMDS_ord5, aes(x=NMDS1, y=NMDS2)) +
        geom_point(size=4, aes(color=QUAD)) + theme_bw() + 
        geom_segment(data=sp_vecs, aes(x=0, xend=MDS1, y=0, yend=MDS2), color="grey", size=1.25,
                     arrow=arrow(length=unit(0.35, "cm"))) +
        geom_text(data=sp_vecs, aes(x=MDS1, y=MDS2, label=Species), size=4) +
        theme(panel.grid.major=element_blank(),
              panel.grid.minor=element_blank())
ord8

# now the plot
ord9 <- ggplot(data=NMDS_ord5, aes(x=NMDS1, y=NMDS2)) +
        geom_point(size=4, aes(color=YEAR)) + theme_bw() + 
        geom_segment(data=sp_vecs, aes(x=0, xend=MDS1, y=0, yend=MDS2), color="grey", size=1.25,
                     arrow=arrow(length=unit(0.35, "cm"))) +
        geom_text(data=sp_vecs, aes(x=MDS1, y=MDS2, label=Species), size=4) +
        theme(panel.grid.major=element_blank(),
              panel.grid.minor=element_blank())
ord9

##
# now the plot
vecs6 <- vegan::envfit(percov_mds5$points, all_treats2[,c(5,8,11)], perm=1000)
vecs6
sp_vecs2 <- as.data.frame(vegan::scores(vecs6, display="vectors"))
sp_vecs2 <- cbind(sp_vecs2, Species = rownames(sp_vecs2))

# now the plot
ord10 <- ggplot(data=NMDS_ord5, aes(x=NMDS1, y=NMDS2)) +
         geom_point(size=4, aes(color=YEAR)) + theme_bw() + 
         geom_segment(data=sp_vecs2, aes(x=0, xend=MDS1, y=0, yend=MDS2), color="grey", size=1.25,
                      arrow=arrow(length=unit(0.35, "cm"))) +
         geom_text(data=sp_vecs2, aes(x=MDS1, y=MDS2, label=Species), size=4) +
         theme(panel.grid.major=element_blank(),
               panel.grid.minor=element_blank())
ord10


# now the plot
ord11 <- ggplot(data=NMDS_ord5, aes(x=NMDS1, y=NMDS2)) +
         geom_point(size=4, aes(color=PDOSign)) + theme_bw() + 
         geom_segment(data=sp_vecs, aes(x=0, xend=MDS1, y=0, yend=MDS2), color="grey", size=1.25,
                     arrow=arrow(length=unit(0.35, "cm"))) +
        geom_text(data=sp_vecs, aes(x=MDS1, y=MDS2, label=Species), size=4) +
         theme(panel.grid.major=element_blank(),
               panel.grid.minor=element_blank())
ord11



```

```{r, echo=FALSE}
percov_perm5

```

### Correlations between env. variables
```{r, echo=FALSE, fig.height=7, fig.width=8}
lmfit_pf <- lm(mn_yr_discharge~PDO_anul_mn, data=PerCov_all)  # lm() fit 

cor_plot1 <- ggplot(data=PerCov_all, aes(x=PDO_anul_mn, y=mn_yr_discharge)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_pf)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_pf$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_pf$coef[[2]], 5),
                              " p =",signif(summary(lmfit_pf)$coef[2,4], 3)))
            


lmfit_pt <- lm(ATemp_YearMn~PDO_anul_mn, data=PerCov_all)  # lm() fit 

cor_plot2 <- ggplot(data=PerCov_all, aes(x=PDO_anul_mn, y=ATemp_YearMn)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_pt)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_pt$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_pt$coef[[2]], 5),
                              " p =",signif(summary(lmfit_pt)$coef[2,4], 3)))
            

lmfit_pw <- lm(PDO_anul_mn~Water_Temp_June, data=PerCov_all)  # lm() fit 

cor_plot2b <- ggplot(data=PerCov_all, aes(x=Water_Temp_June, y=PDO_anul_mn)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_pw)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_pw$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_pw$coef[[2]], 5),
                              " p =",signif(summary(lmfit_pw)$coef[2,4], 3)))
            


lmfit_tf <- lm(ATemp_YearMn~mn_yr_discharge, data=PerCov_all)  # lm() fit 

cor_plot3 <- ggplot(data=PerCov_all, aes(x=mn_yr_discharge, y=ATemp_YearMn)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_tf)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_tf$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_tf$coef[[2]], 5),
                              " p =",signif(summary(lmfit_tf)$coef[2,4], 3)))
            

lmfit_ww <- lm(ATemp_YearMn~Water_Temp_June, data=PerCov_all)  # lm() fit 

cor_plot3b <- ggplot(data=PerCov_all, aes(x=Water_Temp_June, y=ATemp_YearMn)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_ww)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_ww$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_ww$coef[[2]], 5),
                              " p =",signif(summary(lmfit_ww)$coef[2,4], 3)))
            


```

```{r, echo=FALSE, fig.height=8, fig.width=10}
# arranging above plots
grid.arrange(cor_plot2, cor_plot1, cor_plot3b, cor_plot2b, cor_plot3,  ncol=2)

```

### Correlations between other variables
```{r, echo=FALSE, fig.height=6, fig.width=8}
lmfit_tm <- lm(ATemp_YearMn~MYTILUS, data=PerCov_all)  # lm() fit 

cor_plot4 <- ggplot(data=PerCov_all, aes(x=MYTILUS, y=ATemp_YearMn)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_tm)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_tm$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_tm$coef[[2]], 5),
                              " p =",signif(summary(lmfit_tm)$coef[2,4], 3))) +
             theme(plot.title = element_text(size=9))
            


lmfit_tfu <- lm(ATemp_YearMn~FUCUS_PERCOV_TOTAL, data=PerCov_all)  # lm() fit 

cor_plot5 <- ggplot(data=PerCov_all, aes(x=FUCUS_PERCOV_TOTAL, y=ATemp_YearMn)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_tfu)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_tfu$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_tfu$coef[[2]], 5),
                              " p =",signif(summary(lmfit_tfu)$coef[2,4], 3))) +
             theme(plot.title = element_text(size=9))


lmfit_tbn <- lm(ATemp_YearMn~BARNACLES, data=PerCov_all)  # lm() fit 

cor_plot5b <- ggplot(data=PerCov_all, aes(x=BARNACLES, y=ATemp_YearMn)) + 
              geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
              labs(title=paste("Adj R^2 =",signif(summary(lmfit_tbn)$adj.r.squared, 4),
                                #"Intercept =",signif(lmfit_tbn$coef[[1]],5 ),
                                #" Slope =",signif(lmfit_tbn$coef[[2]], 5),
                               " p =",signif(summary(lmfit_tbn)$coef[2,4], 3))) +
             theme(plot.title = element_text(size=10))
            
#####
lmfit_fwm <- lm(mn_yr_discharge~MYTILUS, data=PerCov_all)  # lm() fit 

cor_plot6 <- ggplot(data=PerCov_all, aes(x=MYTILUS, y=mn_yr_discharge)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_fwm)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_fwm$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_fwm$coef[[2]], 5),
                              " p =",signif(summary(lmfit_fwm)$coef[2,4], 3))) +
             theme(plot.title = element_text(size=10)) +
             scale_y_continuous(labels=function(x) sprintf("%.2f", x))
            


lmfit_fwf <- lm(mn_yr_discharge~FUCUS_PERCOV_TOTAL, data=PerCov_all)  # lm() fit 

cor_plot7 <- ggplot(data=PerCov_all, aes(x=FUCUS_PERCOV_TOTAL, y=mn_yr_discharge)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_fwf)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_fwf$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_fwf$coef[[2]], 5),
                              " p =",signif(summary(lmfit_fwf)$coef[2,4], 3))) +
             theme(plot.title = element_text(size=10)) +
             scale_y_continuous(labels=function(x) sprintf("%.2f", x))
            

lmfit_fwb <- lm(mn_yr_discharge~BARNACLES, data=PerCov_all)  # lm() fit 

cor_plot8 <- ggplot(data=PerCov_all, aes(x=BARNACLES, y=mn_yr_discharge)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_fwb)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_fwb$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_fwb$coef[[2]], 5),
                              " p =",signif(summary(lmfit_fwb)$coef[2,4], 3))) +
             theme(plot.title = element_text(size=10)) +
             scale_y_continuous(labels=function(x) sprintf("%.2f", x))
       

lmfit_jm <- lm(Water_Temp_June~MYTILUS, data=PerCov_all)  # lm() fit 

cor_plot9 <- ggplot(data=PerCov_all, aes(x=MYTILUS, y=Water_Temp_June)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_jm)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_jm$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_jm$coef[[2]], 5),
                              " p =",signif(summary(lmfit_jm)$coef[2,4], 3))) +
             theme(plot.title = element_text(size=9))
                 

lmfit_jf <- lm(Water_Temp_June~FUCUS_PERCOV_TOTAL, data=PerCov_all)  # lm() fit 

cor_plot10 <- ggplot(data=PerCov_all, aes(x=FUCUS_PERCOV_TOTAL, y=Water_Temp_June)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_jf)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_jf$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_jf$coef[[2]], 5),
                              " p =",signif(summary(lmfit_jf)$coef[2,4], 3))) +
             theme(plot.title = element_text(size=9))
         

lmfit_jb <- lm(Water_Temp_June~BARNACLES, data=PerCov_all)  # lm() fit 

cor_plot11 <- ggplot(data=PerCov_all, aes(x=BARNACLES, y=Water_Temp_June)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_jb)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_jb$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_jb$coef[[2]], 5),
                              " p =",signif(summary(lmfit_jb)$coef[2,4], 3))) +
             theme(plot.title = element_text(size=9))
                 

```

```{r, echo=FALSE, fig.height=10, fig.width=12}
# arranging above plots
grid.arrange(cor_plot4, cor_plot5, cor_plot5b, ncol=2)
grid.arrange(cor_plot6, cor_plot7, cor_plot8, ncol=2)
grid.arrange(cor_plot9, cor_plot10, cor_plot11, ncol=2)

```

```{r, echo=FALSE, fig.height=3, fig.width=4}
lmfit_fb <- lm(BARNACLES~FUCUS_PERCOV_TOTAL, data=PerCov_all)  # lm() fit 

cor_plot9 <- ggplot(data=PerCov_all, aes(x=FUCUS_PERCOV_TOTAL, y=BARNACLES)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_fb)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_fb$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_fb$coef[[2]], 5),
                              " p =",signif(summary(lmfit_fb)$coef[2,4], 3)))
            
cor_plot9

```


```{r, echo=FALSE}
## MVABUND Results
#anova(glm_percov, p.uni="adjusted")

```

