---
title: "Final Figures"
author: "Rachael E. Blake"
date: "July 28, 2017"
output:
  html_document: default
  pdf_document: default
---


```{r, include=FALSE, echo=FALSE, results='hide'}
library(ggplot2) ; library(tidyverse) ; library(gridExtra) ; library(egg)

```

```{r, echo=FALSE, include=FALSE}
# PDO data
source("PDO_cleaning.r")

# dataframes are pdo_mon and pdo_ann

pdo_mon_adj <- pdo_mon %>%
               mutate(Month_number = forcats::fct_recode(Month, "01"="JAN", "02"="FEB", "03"="MAR",
                                                                "04"="APR", "05"="MAY", "06"="JUN", 
                                                                "07"="JUL", "08"="AUG", "09"="SEP", 
                                                                "10"="OCT", "11"="NOV", "12"="DEC"),
                      Yr_Mn = paste(Year, Month_number, sep="-"),
                      Sign = ifelse(PDO>0, "A", "B"))
               
```

```{r, echo=FALSE}
# PDO plots
pdo_plot <- ggplot(data=pdo_mon, aes(x=Year, y=PDO)) + geom_col() + 
            geom_hline(yintercept=0, size=1.5) + ylab("PDO Index")

  
#
pdo_plot2 <- ggplot(data=pdo_mon_adj, aes(x=Yr_Mn, y=PDO)) + 
             geom_col(aes(fill=Sign)) + xlab("Year") + theme_bw() +            
             geom_hline(yintercept=0, size=1) + ylab("PDO Index") + labs(title="g.") +
             scale_x_discrete(breaks=c("1998-01","1999-01", "2000-01", "2001-01", "2002-01", "2003-01",
                                       "2004-01", "2005-01", "2006-01", "2007-01", "2008-01", "2009-01", 
                                       "2010-01", "2011-01", "2012-01", "2013-01", "2014-01", "2015-01", 
                                       "2016-01"),
                              labels=c("1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005",
                                       "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013",
                                       "2014","2015", "2016")) + 
             theme(panel.grid=element_blank(),
                   legend.title=element_blank(),
                   legend.position="none",
                   axis.text.y=element_text(size=11),
                   axis.text.x=element_text(size=11, angle=35, hjust=0.9),
                   axis.title=element_text(size=13))  

```

```{r, echo=FALSE, include=FALSE}
# Freshwater Discharge Hill Model data
source("Fresh_Discharge_cleaning.r")

# dataframes are FWD_ann_mn and FWD_mon_mn

```

```{r, echo=FALSE}
fwd_plot <- ggplot(data=FWD_ann_mn, aes(x=Year, y=(mean_yearly_anomaly*10))) + 
            geom_col(aes(fill=Sign)) + ylab("Yearly Anomaly") + theme_bw() +
            geom_hline(yintercept=0, size=1) + 
            scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"),
                              name="",
                              labels=c("positive runoff", "negative runoff")) 
 
  
fwd_plot2 <- ggplot(data=FWD_mon_mn, aes(x=Year_Month, y=mean_monthly_anomaly)) + 
             geom_col(aes(fill=Sign)) + xlab("Year") + ylab("Monthly freshwater discharge anomaly") + 
             geom_hline(yintercept=0, size=1) + theme_bw() + ylim(-0.44,0.44) + labs(title="f.") +
             scale_x_discrete(breaks=c("1998-01", "1999-01", "2000-01", "2001-01", "2002-01", "2003-01",
                                       "2004-01", "2005-01", "2006-01", "2007-01", "2008-01", 
                                       "2009-01", "2010-01", "2011-01", "2012-01", "2013-01", 
                                       "2014-01", "2015-01", "2016-01"),
                              labels=c("1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005",
                                       "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013",
                                       "2014","2015", "2016"),
                              limits=c(levels(FWD_mon_mn$Year_Month))) + 
             theme(panel.grid=element_blank(),
                   legend.title=element_blank(),
                   legend.position="none",
                   axis.text.y=element_text(size=11),
                   #axis.text.x=element_text(size=11, angle=35, hjust=0.9),
                   axis.title=element_text(size=13),
                   axis.title.x=element_blank(),
                   axis.text.x=element_blank()) 
                             

```

```{r, echo=FALSE, include=FALSE}
# source air temperature cleaning script
source("AirTemp_cleaning.r")

# dataframes in this script are
# spring_a_temp, summer_a_temp, fall_a_temp, winter_a_temp, ann_a_temp, year_a_temp

```

```{r, echo=FALSE}
# plot of annual air temp anomalies

ann_a_temp$YrMnDy <- as.factor(ann_a_temp$YrMnDy)

ann_a_temp2 <- ann_a_temp %>%
               dplyr::select(YrMn, Month_Anom, Month_Sign) %>%
               dplyr::distinct()

ann_air <- ggplot(data=ann_a_temp2, aes(x=YrMn, y=Month_Anom)) + 
           geom_col(aes(fill=Month_Sign)) + xlab("Year") + labs(title="b.") +
           ylab(expression(paste("Monthly air temperature anomaly (", ~~degree ~C,")"))) +
           geom_hline(yintercept=0, size=1) + theme_bw() + ylim(-16,16) + 
           scale_x_discrete(breaks=c("1999-01", "2000-01", "2001-01", "2002-01","2003-01", 
                                     "2004-01", "2005-01", "2006-01", "2007-01", "2008-01", 
                                     "2009-01", "2010-01", "2011-01", "2012-01", "2013-01", 
                                     "2014-01", "2015-01", "2016-01"),
                            labels=c("1999", "2000", "2001", "2002", "2003", "2004", "2005", 
                                     "2006", "2007", "2008", "2009", "2010", "2011", "2012", 
                                     "2013", "2014","2015", "2016"),
                            limits=c(levels(ann_a_temp$YrMn))) + 
             theme(panel.grid=element_blank(),
                   legend.title=element_blank(),
                   legend.position="none",
                   axis.text.y=element_text(size=11),
                   #axis.text.x=element_text(size=11, angle=35, hjust=0.9),
                   axis.title=element_text(size=13),
                   axis.title.x=element_blank(),
                   axis.text.x=element_blank()) 
 

#ylab(expression(paste(Latitude^o,~'N'))) +
#   ylab(expression(paste("Temperature (", degree ~ C,")"))) + 



```

```{r, echo=FALSE, include=FALSE}
# source water temperature cleaning script
source("WaterTemp_cleaning.r")

# dataframes in this script are
# WTemp_all, WTemp_Yr, WTemp_June, WTemp_Dec, WTemp_Anom

```

#Invertebrates & Algae: 
```{r, include=FALSE, echo=FALSE, results='hide'}
# source the data cleaning script
source("Data_Cleaning_K_Bay_ALL.r")

AllData_clean2 <- AllData_clean %>% 
                  dplyr::select(-FUCUS_NUM_ADULTS, -FUCUS_SPORELINGS_NUM) %>%
                  dplyr::mutate(MASTO_PAP = str_replace_all(MASTO_PAP, ",",""),
                                SIPHONARIA = gsub("[*]", "", SIPHONARIA)) %>%   # STILL A PROBLEM!!!!!!!
                  dplyr::filter(PTEROSIPHONIA != "tr") %>%
                  dplyr::mutate_at(c(5:57), funs(as.numeric)) # converts select columns

  
```

```{r, echo=FALSE}
# dataframe is called AllData_clean

PerCov_long <- AllData_clean2 %>%
               gather(TAXA, PER_COV_OR_COUNT, -YEAR, -TRIPLET, -QUAD, -TREATMENT)

PerCov_anom <- PerCov_long %>%
               dplyr::select(-TRIPLET, -QUAD) %>%
               dplyr::filter(TREATMENT == "CONTROL") %>%
               dplyr::mutate_at(c(4), funs(as.numeric)) %>% # converts select columns
               dplyr::group_by(TAXA) %>%
               dplyr::mutate(TAXA_Mean = mean(PER_COV_OR_COUNT),
                             ANOMALY = PER_COV_OR_COUNT-TAXA_Mean) %>%
               dplyr::ungroup() %>%
               dplyr::group_by(TAXA, YEAR) %>%
               dplyr::mutate(YEAR_Mean = mean(PER_COV_OR_COUNT),
                             YEAR_Anom = mean(YEAR_Mean-TAXA_Mean),
                             YEAR_Anom_Scale = YEAR_Anom/100,
                             YEAR_Anom_Scale2 = YEAR_Anom/10) %>%
               dplyr::ungroup() %>%
               dplyr::arrange(YEAR, TREATMENT, TAXA)

```

```{r, echo=FALSE}

explore_plot1 <- function(y_var){
                 # Define order of the boxes (use this as "fill=" below)
                 AllData_clean2$TREATMENT1 <- factor(AllData_clean2$TREATMENT,
                                                     levels=c("CONTROL","SCRAPE99","SCRAPE00"))
              
                 # format Y axis labels
                 y_label <- paste(toupper(substring(y_var, 1, 1)), tolower(substring(y_var, 2)), sep="")

                
                 p <- ggplot(data=AllData_clean2, aes_string(x="YEAR", y=y_var, fill="TREATMENT1")) + 
                      geom_boxplot() + theme(legend.position="top", legend.title=element_blank()) + 
                      theme_bw() + xlab("Year") + ylim(0,100) +
                      ylab(paste(y_label, " percent cover", sep = "")) + 
                      scale_fill_manual(breaks=c("CONTROL","SCRAPE99","SCRAPE00"),
                                        labels=c("Control","Scrape 1999","Scrape 2000"),
                                        values=c("#76eec6","#63b8ff","#ff6a6a")) + 
                      theme(panel.grid=element_blank(),
                            legend.title=element_blank(),
                            legend.position=c(.95, .55),
                            #legend.position="top",
                            #legend.position="none",
                            legend.justification=c(1,0),
                            legend.text=element_text(size=11),
                            axis.text.y=element_text(size=11),
                            axis.text.x=element_text(size=11, angle=35, hjust=0.9),
                            axis.title=element_text(size=13))

                 return(p)
}
#
    
explore_plot2 <- function(y_var){
                 # Define order of the boxes (use this as "fill=" below)
                 AllData_clean2$TREATMENT1 <- factor(AllData_clean2$TREATMENT,
                                                     levels=c("CONTROL","SCRAPE99","SCRAPE00"))
                 
                 # format Y axis labels
                 y_label <- paste(toupper(substring(y_var, 1, 1)), tolower(substring(y_var, 2)), sep="")
                 
                 
                 q <- ggplot(data=AllData_clean2, aes_string(x="YEAR", y=y_var, fill="TREATMENT1")) + 
                      geom_boxplot() + theme(legend.position="top", legend.title=element_blank()) + 
                      theme_bw() + xlab("Year") + 
                      ylab(paste("Number of ", y_label)) + 
                      scale_fill_manual(breaks=c("CONTROL","SCRAPE99","SCRAPE00"),
                                        labels=c("Control","Scrape 1999","Scrape 2000"),
                                        values=c("#76eec6","#63b8ff","#ff6a6a")) + 
                      theme(panel.grid=element_blank(),
                            legend.title=element_blank(),
                            #legend.position=c(.95, .55),
                            legend.position="none",
                            legend.justification=c(1,0),
                            legend.text=element_text(size=11),
                            axis.text.y=element_text(size=11),
                            axis.text.x=element_text(size=11, angle=35, hjust=0.9),
                            axis.title=element_text(size=13))
                  
                 return(q)
}       
#

    
explore_plot3 <- function(y_var){
                 # format Y axis labels
                 y_label <- paste(toupper(substring(y_var, 1, 1)), tolower(substring(y_var, 2)), sep="")
                 
                 # have to define my own standard error function because one doesn't exist in base R!!!
                 se <- function(x) sqrt(var(x)/length(x))
                 
                 # subset only to CONTROLs, calculate SD and SE for each species in each year
                 CONTData_clean <- AllData_clean2 %>%
                                   dplyr::filter(TREATMENT == "CONTROL") %>%
                                   dplyr::select(TRIPLET, QUAD, TREATMENT, YEAR, BARNACLE_SPAT, BARNACLES, 
                                                 FUCUS_PERCOV_TOTAL, FUCUS_SPORELINGS_PERCOV, MYTILUS,
                                                 PTEROSIPHONIA, L.SITKANA, LOTTIIDAE) %>%
                                   group_by(YEAR) %>%
                                   mutate_at(vars(BARNACLE_SPAT:LOTTIIDAE), funs(Mean=mean), na.rm=TRUE) %>%
                                   mutate_at(vars(BARNACLE_SPAT:LOTTIIDAE), funs(SD=sd), na.rm=TRUE) %>%
                                   mutate_at(vars(BARNACLE_SPAT:LOTTIIDAE), funs(SE=se)) %>%
                                   ungroup()
                 
                 # making the error bar min and max
                 y_axis <- as.name(paste(y_var, "_Mean", sep=""))
                 SE_name <- as.name(paste(y_var, "_SE", sep=""))
                 ymins <- paste(y_axis, SE_name, sep='-')
                 ymaxs <- paste(y_axis, SE_name, sep='+')
              #   bars <- aes_string(ymin=y_axis-SE_name, ymax=y_axis+SE_name, width=.2)

                 
                 b <- ggplot(data=CONTData_clean, aes_string(x="YEAR", y=y_axis, group=1)) + 
                      geom_point(size=3) + geom_line(size=1) + theme_bw() + xlab("Year") +
                      geom_errorbar(data=CONTData_clean, 
                                    aes_string(ymin=ymins, ymax=ymaxs, width=.2)) +   
                      ylab(y_label) +
                      theme(panel.grid=element_blank(),
                            legend.title=element_blank(),
                            axis.text.y=element_text(size=11),
                            axis.text.x=element_text(size=11, angle=35, hjust=0.9),
                            axis.title=element_text(size=13))#,
                           # axis.title.x=element_text(),
                            #axis.text.x=element_blank())
                  
                 return(b)
} 


```

```{r, echo=FALSE, fig.height=4, fig.width=7, warning=FALSE}
# Fucus Total
# ft <- explore_plots("FUCUS_TOTAL")
# ft

# make a plot for each variable
# FUCUS_PERCOV_TOTAL_scaled , FUCUS_SPORELINGS_PERCOV , MYTILUS , PTEROSIPHONIA , BARNACLES , BARNACLE_SPAT
var_names <- names(AllData_clean2[,c(8,9,26,27,42,54)])  

PerCov_Plots <- lapply(var_names, function(x) FUN=explore_plot1(y_var=x))

BARN_SPAT_plot <- PerCov_Plots[[1]] + ylab("Barnacle spat % cover") + labs(title="a.") +
                  theme(legend.position="none", axis.title.x=element_blank(), axis.text.x=element_blank())  
BARN_plot <- PerCov_Plots[[2]] + ylab("Barnacle % cover") + labs(title="c.") +
             theme(legend.position="none", axis.title.x=element_blank(), axis.text.x=element_blank()) 
FUCUS_plot <- PerCov_Plots[[3]] + ylab(expression(paste(italic("Fucus"), " % cover"))) + labs(title="d.") +
              theme(legend.position="none", axis.title.x=element_blank(), axis.text.x=element_blank()) 
FUC_SPORE_plot <- PerCov_Plots[[4]] + ylab(expression(paste(italic("Fucus"), " sporeling % cover")))  + 
                  labs(title="b.") + theme(legend.position="none", axis.title.x=element_blank(),
                                           axis.text.x=element_blank()) 
MUSS_plot <- PerCov_Plots[[5]] + ylab(expression(paste(italic("Mytilus"), " % cover"))) + labs(title="e.") +
             theme(legend.position="none", axis.title.x=element_blank(), axis.text.x=element_blank()) 
PTERO_plot <- PerCov_Plots[[6]] + ylab(expression(paste(italic("Pterosi. "), " complex % cover"))) +
              labs(title="f.") +
              theme(axis.title.x=element_blank(), axis.text.x=element_blank())

##
# make a plot for each variable
#LOTTIIDAE_scaled , L.SITKANA_scaled 
var_names2 <- names(AllData_clean2[,c(33,37)])  

Count_Plots <- lapply(var_names2, function(x) FUN=explore_plot2(y_var=x))

SNAIL_plot <- Count_Plots[[1]] + ylab(expression(paste(italic("L. sitkana"), " abundance"))) + labs(title="g.") 
LIMP_plot <- Count_Plots[[2]] + ylab(expression(paste(italic("Lottiidae"), " abundance"))) + labs(title="h.") 


```

```{r, echo=FALSE, fig.height=12, fig.width=12}
# arranging above plots
# grid.arrange(BARN_SPAT_plot, FUC_SPORE_plot, BARN_plot, FUCUS_plot, MUSS_plot, PTERO_plot, 
#              SNAIL_plot, LIMP_plot, ncol=2)

ggarrange(BARN_SPAT_plot, FUC_SPORE_plot, BARN_plot, FUCUS_plot, MUSS_plot, PTERO_plot, 
          SNAIL_plot, LIMP_plot, ncol=2)

```

```{r, echo=FALSE, fig.height=4, fig.width=7, warning=FALSE}
# make a plot for each variable
var_names3 <- names(AllData_clean2[,c(8,9,26,27,33,37,42,54)]) 

Line_Plots <- lapply(var_names3, function(x) FUN=explore_plot3(y_var=x))

BS_line <- Line_Plots[[1]] + ylab("Barnacle spat % cover") + ylim(0,100) + labs(title="a.") +
           theme(legend.position="none", axis.title.x=element_blank(), axis.text.x=element_blank()) 
BN_line <- Line_Plots[[2]] + ylab("Barnacle % cover") + ylim(0,100) + labs(title="c.") +
           theme(legend.position="none", axis.title.x=element_blank(), axis.text.x=element_blank()) 
FU_line <- Line_Plots[[3]] + ylab(expression(paste(italic("Fucus"), " % cover"))) + ylim(0,100) + 
           labs(title="d.") + theme(legend.position="none", axis.title.x=element_blank(),
                                    axis.text.x=element_blank()) 
FS_line <- Line_Plots[[4]] + ylab(expression(paste(italic("Fucus"), " sporeling % cover"))) + ylim(0,100) +
           labs(title="b.") + theme(legend.position="none", axis.title.x=element_blank(),
                                    axis.text.x=element_blank())
SN_line <- Line_Plots[[5]] + ylab(expression(paste(italic("L. sitkana"), " abundance"))) + labs(title="g.")  
LP_line <- Line_Plots[[6]] + ylab(expression(paste(italic("Lottiidae"), " abundance"))) + labs(title="h.") 
MS_line <- Line_Plots[[7]] + ylab(expression(paste(italic("Mytilus"), " % cover"))) + ylim(0,100) +
           labs(title="e.") + theme(legend.position="none", axis.title.x=element_blank(),
                                    axis.text.x=element_blank())
PT_line <- Line_Plots[[8]] + ylab(expression(paste(italic("Pterosi."), " complex % cover"))) +
           ylim(0,100) +
           labs(title="f.") + theme(legend.position="none", axis.title.x=element_blank(),
                                    axis.text.x=element_blank())


```

```{r, echo=FALSE, fig.height=12, fig.width=12}
# arranging above plots
#grid.arrange(BS_line,FS_line,BN_line,FU_line,MS_line,PT_line,SN_line,LP_line, ncol=2)

ggarrange(BS_line,FS_line,BN_line,FU_line,MS_line,PT_line,SN_line,LP_line, ncol=2)

```



#Environmental Drivers:
```{r, echo=FALSE}
# NOTE: Error bars are standard error
WT_plot1 <- ggplot(data=WTemp_June, aes(x=Year, y=Water_Temp_June, group=1)) + 
            geom_point(size=3) + geom_line(size=1) + theme_bw() + ylim(0,10.5) +
            geom_errorbar(aes(ymin=Water_Temp_June-Water_Temp_Monthly_SE,
                              ymax=Water_Temp_June+Water_Temp_Monthly_SE), width=.2) +
            ylab(expression(paste("June water temperature ( ", degree ~ C,")"))) + labs(title="c.") +
            theme(panel.grid=element_blank(),
                  legend.title=element_blank(),
                  axis.text.y=element_text(size=11),
                  #axis.text.x=element_text(size=11, angle=35, hjust=0.9),
                  axis.title=element_text(size=13),
                  axis.title.x=element_blank(),
                  axis.text.x=element_blank())
##
AT_plot1 <- ggplot(data=year_a_temp, aes(x=Year, y=ATemp_YearMn, group=1)) + 
            geom_point(size=3) + geom_line(size=1) + theme_bw() + ylim(0,10.5) +
            geom_errorbar(aes(ymin=ATemp_YearMn-ATemp_YearSE,
                              ymax=ATemp_YearMn+ATemp_YearSE), width=.2) + 
            ylab(expression(paste("Annual air temperature ( ", degree ~ C,")"))) + labs(title="a.") +
            theme(panel.grid=element_blank(),
                  legend.title=element_blank(),
                  axis.text.y=element_text(size=11),
                  #axis.text.x=element_text(size=11, angle=35, hjust=0.9),
                  axis.title=element_text(size=13),
                  axis.title.x=element_blank(),
                  axis.text.x=element_blank())
##
FWD_plot1 <- ggplot(data=FWD_ann_mn, aes(x=Year, y=mean_yearly_discharge_m3s1, group=1)) + 
             geom_point(size=3) + geom_line(size=1) + theme_bw() + labs(title="e.") +
             geom_errorbar(aes(ymin=mean_yearly_discharge_m3s1-SE_yearly_discharge_m3s1,
                               ymax=mean_yearly_discharge_m3s1+SE_yearly_discharge_m3s1), width=.2) + 
             ylab(expression(paste("Annual freshwater discharge ( ", m^3, s^-1,")"))) +
             theme(panel.grid=element_blank(),
                   legend.title=element_blank(),
                   axis.text.y=element_text(size=11),
                   axis.text.x=element_text(size=11, angle=35, hjust=0.9),
                   axis.title=element_text(size=13))
##
## anomaly plot of water temp
WT_plot_anom <- ggplot(data=WTemp_Anom, aes(x=YrMn, y=Water_Temp_Anom)) +
                geom_col(aes(fill=Month_Sign)) + xlab("Year") + ylim(7,-7) + labs(title="d.") +
                ylab(expression(paste("Monthly water temperature anomaly (", ~~degree ~C,")"))) +
                geom_hline(yintercept=0, size=1) + theme_bw() +
                scale_x_discrete(breaks=c("1999-01", "2000-01", "2001-01", "2002-01","2003-01", 
                                          "2004-01", "2005-01", "2006-01", "2007-01", "2008-01", 
                                          "2009-01", "2010-01", "2011-01", "2012-01", "2013-01", 
                                          "2014-01", "2015-01", "2016-01"),
                                 labels=c("1999", "2000", "2001", "2002", "2003", "2004", "2005", 
                                          "2006", "2007", "2008", "2009", "2010", "2011", "2012", 
                                          "2013", "2014","2015", "2016"),
                                 limits=c(levels(WTemp_Anom$YrMn))) + 
                theme(panel.grid=element_blank(),
                      legend.title=element_blank(),
                      legend.position="none",
                      axis.text.y=element_text(size=11),
                      #axis.text.x=element_text(size=11, angle=35, hjust=0.9),
                      axis.title=element_text(size=13),
                      axis.title.x=element_blank(),
                      axis.text.x=element_blank()) 

       
    
# create blank ggplot for final figure
df <- data.frame()
blank_plot <- ggplot(df) + theme(panel.background = element_blank())
  
```

```{r, echo=FALSE, fig.height=20, fig.width=15, warning=FALSE}
# arranging above plots
#grid.arrange(WT_plot1, FWD_plot1, AT_plot1, ncol=2)

ggarrange(AT_plot1, ann_air, WT_plot1, WT_plot_anom, FWD_plot1, fwd_plot2, blank_plot, pdo_plot2, ncol=2)

```

# NMDS:
```{r, echo=FALSE, include=FALSE}
source("NMDS_analysis.r")

# need to use NMDS output percov_mds$points

```

```{r, echo=FALSE, fig.height=7, fig.width=8}
# prettier plotting
# build a data frame with NMDS coordinates and metadata
NMDS_ord <- data.frame(NMDS1 = percov_mds$points[,1], NMDS2 = percov_mds$points[,2],
                       PDO_Sign = PerCov_PDO$PDO_Sign, YEAR = PerCov_PDO$Year)

find_hull <- function(df) df[chull(df$NMDS1, df$NMDS2), ]
hulls <- ddply(NMDS_ord, "PDO_Sign", find_hull)

# now the plot
ord1 <- ggplot(NMDS_ord, aes(x=NMDS1, y=NMDS2, color=PDO_Sign)) +
        geom_point() + #stat_ellipse() +
        geom_polygon(data = hulls, alpha = 0.3, aes(fill=PDO_Sign)) +
        theme_bw() +
        scale_color_manual(values=c("A"="#f88379", "B"="#00BFC4"), name="",
                           labels=c("positive PDO","negative PDO")) + 
        scale_fill_manual(values=c("A"="#f88379", "B"="#00BFC4"), name="",
                          labels=c("positive PDO","negative PDO")) + 
        theme(panel.grid.major=element_blank(),
              panel.grid.minor=element_blank(),
              axis.text.y=element_text(size=11),
              axis.text.x=element_text(size=11, hjust=0.5),
              axis.title=element_text(size=13))
ord1


```







