## Testing netCDF file subsetting on read-in


### load necessary packages
library(ncdf4) ; library(chron) ; library(dplyr) ; library(forcats) ; library(ggplot2)

# download the really large file
download.file("http://thredds.aoos.org/thredds/dodsC/GOA_RUNOFF_DISCHARGE.ncml.html",
              destfile = "/research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE.nc")

# #### Using `gdalUtilities` from here: https://github.com/JoshOBrien/gdalUtilities/
# library(gdalUtilities)
# gdalwarp(srcfile = "/research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE.nc",
#          dstfile = "/research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE_studyarea.nc",
#          te = c(-151.40, 59.44, -151.63, 59.54))#, dryrun = TRUE) 
# # dryrun = TRUE checks that your R specification is correct command-line syntax
# 
# library(sf)
# gdal_utils(util = "warp", 
#            source = "/research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE.nc",
#            destination = "/research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE_studyarea.nc",
#            options = c("-te", "-151.40 59.44 -151.63 59.54"))

# using stars packages
# library(stars)
# nc_kbay <- read_ncdf("/research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE.nc")
# says "Error in RNetCDF::open.nc(x) : NetCDF: Unknown file format"
# This function can read from the URL, but still have the same problem...too big 155.6 Gb

### read in the netcdf file and parse and clean the parts
# nc_kbay <- nc_open("GOA_RUNOFF_DISCHARGE.ncml.nc") # uses a static file downloaded in 2017
# nc_kbay <- nc_open("http://thredds.aoos.org/thredds/dodsC/GOA_RUNOFF_DISCHARGE.ncml") # download directly from OPeNDAP
# nc_kbay <- nc_open("GOA_RUNOFF_DISCHARGE_studyarea.nc") 
# print(nc_kbay)
# names(nc_kbay$dim) #display dimensions
# names(nc_kbay$var) #display variables

# get latitude
latitude_deg_north <- ncvar_get(nc_kbay, "lat")
lat_lname <- ncatt_get(nc_kbay, "lat", "long_name")
lat_units <- ncatt_get(nc_kbay, "lat", "units")

# get longitude
longitude_deg_east <- ncvar_get(nc_kbay, "lon")
lon_lname <- ncatt_get(nc_kbay, "lon", "long_name")
lon_units <- ncatt_get(nc_kbay, "lon", "units")

### make a lat lon dataframe
latlon <- as.data.frame(matrix(ncol=0, nrow=1629000))
latlon$latitude_deg_north <- as.vector(latitude_deg_north)
latlon$longitude_deg_east <- as.vector(longitude_deg_east)
# ggplot(data = latlon, aes(x=longitude_deg_east, y=latitude_deg_north)) + geom_tile() + coord_equal()

# # lat and lon range for area I need (values taken from old file subsetted in 2017)
# > min(plot_df$as.vector.latitude_deg_north.)
# [1] 59.45683
# > max(plot_df$as.vector.latitude_deg_north.)
# [1] 59.532
# > min(plot_df$as.vector.longitude_deg_east.)
# [1] -151.6191
# > max(plot_df$as.vector.longitude_deg_east.)
# [1] -151.419

latrange <- c(59.44, 59.54)
lonrange <- c(-151.63, -151.40) 
  
# ggplot(latlon, aes(x = latitude_deg_north, y = longitude_deg_east))
#######################################
# try using gdal at the linux system level
system(gdalwarp GOA_RUNOFF_DISCHARGE.nc GOA_RUNOFF_DISCHARGE_studyarea.nc -te -151.63 59.44 -151.40 59.54)

# generated by gdalUtilities package
system(gdalwarp /research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE.nc /research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE_studyarea.nc -te -151.4 59.44 -151.63 59.54)
#################
# try on the command line using cdo
# cdo sellonlatbox,-96.5,-89,40,43 in.nc out.nc
system(cdo sellonlatbox, -151.63, -151.40, 59.44, 59.54 /research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE.nc /research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE_studyarea.nc)
# produces ERROR: "Error in system(cdo - sellonlatbox, -151.4, -151.63, 59.44, 59.54/research - : 'intern' must be TRUE or FALSE"
# produced error: Error: unexpected symbol in "system(cdo sellonlatbox"
################
# try to use command line ncks
# ncks -v air -d latitude,40.,43. -d longitude,-89.,-96. infile.nc -O subset_infile.nc
system(ncks -v q -d lat,59.44,59.54 -d lon,-151.63,-151.40 /research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE.nc -0 /research-home/rblake/Klinger_Kasitsna_Bay/GOA_RUNOFF_DISCHARGE_studyarea.nc)
# produced error: Error: unexpected symbol in "system(ncks -v q"

##################
# # using `processNC` package from here: https://github.com/RS-eco/processNC
# library(processNC)

# subsetNC(files = "http://thredds.aoos.org/thredds/dodsC/GOA_RUNOFF_DISCHARGE.ncml",
#          ext = c(-151.40, 59.44, -151.63, 59.54),
#          # startdate = 1999, enddate = 2021,
#          filename = "GOA_RUNOFF_DISCHARGE_2021.nc")
# 
# 
#####################################
# using tidy nc to try to subset the data
# library(tidync)
# 
# src <- tidync("http://thredds.aoos.org/thredds/dodsC/GOA_RUNOFF_DISCHARGE.ncml")
# print(src)
#
# # subsetting
# latrange <- c(59.44, 59.54)
# lonrange <- c(-151.63, -151.40) # lat and lon range for area I need
#
#
# src_sub <- src %>%
#            hyper_tibble() %>% 
#            dplyr::filter(lat = lat > 59.44 & lat < 59.54) %>% 
#            dplyr::filter(lon = lon > -151.63 & lon < -151.40)
# 
# src_sub
# 
# This doesn't work: results in:
# Error in hyper_filter.tidync(., x = x > latrange[1] & x <= latrange[2],  : 
#   subexpression for [x] results in empty slice

# Tried many permutations based on the info here:https://docs.ropensci.org/tidync/articles/netcdf-with-tidync.html#data-extraction-1
# ALL FAILED TO EXTRACT THE DATA!!!!!!

####################################
# # https://stackoverflow.com/questions/21280104/how-to-take-a-subset-from-a-netcdf-file-using-latitude-longitude-boundaries-in-r
# LonIdx <- which(nc_kbay$var$lon$vals > 59.44 & nc_kbay$float$lon$vals < 59.54)
# LatIdx <- which(nc_kbay$float$latn$vals > -151.40 | nc_kbay$float$lat$vals < -151.63)
# MyVariable <- ncvar_get(nc_kbay, "q")[LonIdx, LatIdx]
# 
# # nc_kbay$var$lon$vals and the various permutations I've tried always returns NULL!!! So no solution here.
# nc_kbay$dim$time$vals  # actually shows values
# nc_kbay$var$lat$vals  # still shows NULL!!!!!!!!!!!


nc_kbay$var$lat$dim # this produces something
nc_kbay$var$lon$dim
nc_kbay$var$q$dim
nc_kbay$dim$x$vals # just produces numbers from 1:1810, not the longitude(x) values!!!!
####################################


