---
title: "Chla_Indicator"
output:
  pdf_document: default
  html_document: default
---


```{r, echo=FALSE, message=FALSE, include=FALSE}
library(tidyverse) ; library(psych) ; library(gridExtra) ; library(here)

```

```{r , echo=FALSE, message=FALSE}
# get the Chla data

chl <- read.csv(here("./data_clean/chl_all_monthly_clean.csv"), stringsAsFactors = FALSE,
                header = TRUE, row.names = NULL, strip.white = TRUE)

chl_monthly <- chl %>% 
               select(Year, Month, Chl_Month_Mn)


```

```{r, echo=FALSE, message=FALSE, include=FALSE}
# get the water temp data
w_temp <- read.csv(here("./data_clean/WTemp_all_clean.csv"), stringsAsFactors = FALSE,
                   header = TRUE, row.names = NULL, strip.white = TRUE)

WTemp_monthly <- w_temp %>%
                 select(Year, Month, Water_Temp_Monthly, Month_Sign) %>% 
                 filter(!Water_Temp_Monthly == 999.000000)

```

```{r, echo=FALSE, message=FALSE, include=FALSE}
# get the air temp data
a_temp <- read.csv(here("./data_clean/air_temp_annual_clean.csv"), stringsAsFactors = FALSE,
                   header = TRUE, row.names = NULL, strip.white = TRUE)

Atemp_monthly <- a_temp %>%
                 select(year, month, ATemp_monthMn) %>%
                 rename(Year = year, Month = month) %>% 
                 distinct() 
                 

```

```{r, echo=FALSE, message=FALSE, include=FALSE}
# get the freshwater discharge data
FWD_mon_mn <- read.csv(here("./data_clean/FWD_monthly_mn_clean.csv"), stringsAsFactors = FALSE,
                       header = TRUE, row.names = NULL, strip.white = TRUE)

FWD_monthly <- FWD_mon_mn %>%
               select(-Year_Month, -Year_Month2, -Sign, -mean_monthly_anomaly) %>%
               mutate(Month = str_replace_all(Month, "Jan", "01"),
                      Month = str_replace_all(Month, "Feb", "02"),
                      Month = str_replace_all(Month, "Mar", "03"),
                      Month = str_replace_all(Month, "Apr", "04"),
                      Month = str_replace_all(Month, "May", "05"),
                      Month = str_replace_all(Month, "Jun", "06"),
                      Month = str_replace_all(Month, "Jul", "07"),
                      Month = str_replace_all(Month, "Aug", "08"),
                      Month = str_replace_all(Month, "Sep", "09"),
                      Month = str_replace_all(Month, "Oct", "10"),
                      Month = str_replace_all(Month, "Nov", "11"),
                      Month = str_replace_all(Month, "Dec", "12")) %>%
               mutate(across(c(1,2), as.integer)) # converts select columns

```


```{r, echo=FALSE}
# plot timeline of chl variable

every_nth = function(n) {
  return(function(x) {x[c(TRUE, rep(FALSE, n - 1))]})
}


line_plot <- chl_monthly %>% 
             mutate(Month = str_pad(Month, width = 2, side = "left", pad = "0")) %>% 
             mutate(Yr_Month = paste0(Year, "_", Month)) %>% 
             ggplot() + theme_bw() +
             geom_line(aes(x = Yr_Month, y = Chl_Month_Mn), group = 1) +
             theme(axis.text.x = element_text(angle = 45, vjust=1, hjust=1)) + 
             scale_x_discrete(breaks = every_nth(n = 6))
             

line_plot

```


```{r, echo=FALSE, message=FALSE, include=FALSE}

PerCov_CHL_WQ <- Atemp_monthly %>%
                 full_join(WTemp_monthly, by = c("Year", "Month")) %>%  # join other data
                 # filter(Year %in% c("2007", "2008", "2011", "2012", "2013", 
                 #                    "2014", "2015")) %>%
                 full_join(FWD_monthly, by = c("Year", "Month")) %>%  # join other data
                 filter(#Year %in% c("2007", "2008", "2011", "2012", "2013", 
                         #          "2014", "2015"),
                               !is.na(Water_Temp_Monthly),
                               mean_monthly_discharge_m3d1 != 0.000000100) %>%
                 arrange(Year, Month) %>%
                 full_join(chl_monthly , by = c("Year", "Month")) %>%  # join other data
                 filter(Year %in% c(2002:2020),
                        !is.na(Chl_Month_Mn),
                        !is.na(Water_Temp_Monthly)
                        ) %>%
                 mutate(Chl_Month_LOG = log(Chl_Month_Mn))

```

```{r, echo=FALSE}

pairs.panels(PerCov_CHL_WQ[,c(3, 4, 6, 7)], smooth = F, density = T, ellipses = F, lm = T, 
             digits = 3, scale = T)


```

```{r, echo=FALSE, message=FALSE}
lmfit_cat <- lm(Chl_Month_LOG ~ ATemp_monthMn, data = PerCov_CHL_WQ)  # lm() fit 

cor_plotA <- ggplot(data=PerCov_CHL_WQ, aes(x=ATemp_monthMn, y=Chl_Month_LOG)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_cat)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_cat$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_cat$coef[[2]], 5),
                              " p =",signif(summary(lmfit_cat)$coef[2,4], 4)))
            


lmfit_cwt <- lm(Chl_Month_LOG ~ Water_Temp_Monthly, data = PerCov_CHL_WQ)  # lm() fit 

cor_plotB <- ggplot(data=PerCov_CHL_WQ, aes(x=Water_Temp_Monthly, y=Chl_Month_LOG)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_cwt)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_cwt$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_cwt$coef[[2]], 5),
                              " p =",signif(summary(lmfit_cwt)$coef[2,4], 3)))
            


lmfit_cfw <- lm(Chl_Month_LOG ~ mean_monthly_discharge_m3d1, data = PerCov_CHL_WQ)  # lm() fit 

cor_plotC <- ggplot(data=PerCov_CHL_WQ, aes(x=mean_monthly_discharge_m3d1, y=Chl_Month_LOG)) + 
             geom_point(size=4) + stat_smooth(method="lm", col="pink") + theme_bw() +
             labs(title=paste("Adj R^2 =",signif(summary(lmfit_cfw)$adj.r.squared, 4),
                               #"Intercept =",signif(lmfit_cfw$coef[[1]],5 ),
                               #" Slope =",signif(lmfit_cfw$coef[[2]], 5),
                              " p =",signif(summary(lmfit_cfw)$coef[2,4], 3)))
            



```

```{r, echo=FALSE, fig.height=7, fig.width=8}
# arranging above plots
grid.arrange(cor_plotA, cor_plotB, cor_plotC, nrow = 2)

```

```{r, echo=FALSE, fig.height=7, fig.width=8}
PerCov_CHL_WQ_sub <- dplyr::select(PerCov_CHL_WQ, -Year, -Month, -Month_Sign)

WQ_pca <- prcomp(PerCov_CHL_WQ_sub, scale. = T)

biplot(WQ_pca, scale = 0)

```











